swagger: '2.0'
info:
  title: Service Broker API
  description:
    This API describes the interaction between a platform and a
    service broker. the broker implements these endpoints.
  version: "2.10.0"
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

schemes:
  - http

basePath: /v2

consumes:
  - application/json
produces:
  - application/json

paths:
  /catalog:
    get:
      summary: Registered services
      responses:
        200:
          description: list of services
          schema:
            type: array
            items:
              $ref: '#/definitions/Service'

  '/service_instances/{instance_id}':
    parameters:
      - $ref : '#/parameters/instance_id'
#    put:
#    patch:
    delete:
      summary: deprovisions the instance
      responses:
        200:
          description: instance was deleted

  "/service_instances/{instance_id}/service_binding/{binding_id}":
    parameters:
      - $ref : '#/parameters/instance_id'
      - name: binding_id
        in: path
        required: true
        type: string
#   put:
    delete:
      summary: unbinds the service
      responses:
        200:
          description: service was unbound

parameters:
  instance_id:
    name: instance_id
    type: string
    in: path
    required: true

definitions:
  Service:
    type: object
    required:
      - name
      - id
      - description
      - plans
    properties:
      name:
        type: string
      id:
        type: string
      description:
        type: string
      bindable:
        type: boolean
      plans:
        type: array
        items:
          $ref: '#/definitions/Plan'
  Plan:
    type: object
    required:
      - id
      - name
      - description
      - free
    properties:
      id:
        type: string
      name:
        type: string
      description:
        type: string
      free:
        type: boolean
